.\" Manpage for mkchain.
.\" Contact trimstray@gmail.com.
.TH man 8 "22.01.2018" "1.5.1" "mkchain man page"
.SH NAME
mkchain \- Open source tool to help you build a valid SSL certificate chain.
.SH SYNOPSIS
mkchain <option|long-option>
.SH DESCRIPTION
Is an open source tool to help you build a valid SSL certificate chain from the root certificate to the end-user certificate. Also can help you fix the incomplete certificate chain and download all missing CA certificates.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

-i, --in
        add certificates to merge (file, multiple files, directory with ssl certificates
        or remote domain)

-o, --out
        saves the result (chain) to a file

--with-root
        add root certificate to certificates chain
.SH SEE ALSO
https://github.com/trimstray/mkchain
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
