.\" Manpage for sslmerge.
.\" Contact trimstray@gmail.com.
.TH man 8 "22.01.2018" "1.4.2" "sslmerge man page"
.SH NAME
sslmerge \- Open source tool to help you build a valid SSL certificate chain.
.SH SYNOPSIS
sslmerge <option|long-option>
.SH DESCRIPTION
Is an open source tool to help you build a valid SSL certificate chain from the root certificate to the end-user certificate. Also can help you fix the incomplete certificate chain and download all missing CA certificates.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

-i, --in
        add certificates to merge (file, multiple files or directory with ssl certificates)

-o, --out
        saves the result (chain) to a file

--with-root
        add root certificate to certificates chain
.SH SEE ALSO
https://github.com/trimstray/sslmerge
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
