.\" Manpage for git-template-full.
.\" Contact contact@nslab.at.
.TH man 8 "00.00.0000" "1.0.0" "git-template-full man page"
.SH NAME
git-template-full \- short script description
.SH SYNOPSIS
git-template-full <option|long-option>
.SH DESCRIPTION
git-template-full short long description.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

--verbose
        displays 'info' messages on the screen (verbose mode)

--time
        displays execution time, occurs only with --verbose

-c, --config <file>
        attach an external config file to the script
.SH SEE ALSO
https://github.com/trimstray/git-template-full
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
