#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: sslChainRelation()
#
# Description:
#   Set relationship between certificates.
#
# Usage:
#   sslChainRelation
#
# Examples:
#   sslChainRelation
#

function sslChainRelation() {

  local _FUNCTION_ID="sslChainRelation"
  local _STATE=0

  local _ssl_attr_num="0"
  local _ssl_keep_num="0"

  _key_type_ident="false"
  _key_type_root="false"
  _key_type_inter="false"

  _key_type_inter_count="0"
  _key_type_root_inter="false"
  _key_type_root_inter_visible="false"

  echo

  printf "  \\e[1;34m%s\\e[m:\\n\\n" "SSL certificate chain"

  # shellcheck disable=SC2154
  while [[ "$_ssl_attr_num" -lt "${#ssl_attr[@]}" ]] ; do

    # Extracting data for each element of the array.
    for i in "${ssl_attr[@]}" ; do

    if [[ "$_ssl_keep_num" -lt "${#ssl_attr[@]}" ]] ; then

      _key_path=$(echo "$i" | awk -v FS="(:|:)" '{print $1}')
      _key_path_name="$(basename "$_key_path")"
      _key_issuer=$(echo "$i" | awk -v FS="(:|:)" '{print $2}')
      _key_subject=$(echo "$i" | awk -v FS="(:|:)" '{print $3}')
      _key_issuer_hash=$(echo "$i" | awk -v FS="(:|:)" '{print $4}')
      _key_subject_hash=$(echo "$i" | awk -v FS="(:|:)" '{print $5}')

      _key_issuer_filter=$(echo "$_key_issuer" | sed 's/  *//g')
      _key_subject_filter=$(echo "$_key_subject" | sed 's/  *//g')

      _logger "info" \
        "$_FUNCTION_ID()" \
        "extracting items from ${i} => 0:${_key_path}, 1:${_key_issuer}, 2:${_key_subject}, 3:${_key_issuer_hash}, 4:${_key_subject_hash}"

      # Compares the current field 'Subject' certificate processed
      # on the last field 'Subject' of the previous certificate.
      if [[ "$_key_subject_filter" == "$_last_subject" ]] ; then

        if [[ "$_last_subject" == *"."* ]] ; then

          # shellcheck disable=SC2034
          _key_type="Identity Certificate"
          # shellcheck disable=SC2034
          _key_type_ident="true"

        elif [[ "$_last_subject" == "$_key_issuer_filter" ]] ; then

          # shellcheck disable=SC2034
          _key_type="Root Certificate"
          # shellcheck disable=SC2034
          _key_type_root="true"

        elif [[ "$_last_subject" != "$_key_issuer_filter" ]] ; then

          # shellcheck disable=SC2034
          _key_type="Intermediate Certificate"
          # shellcheck disable=SC2034
          _key_type_inter="true"

          _key_type_inter_count=$((_key_type_inter_count + 1))

        else

          _key_type="Unknown Certificate"

        fi

        # Assign an element to the array with 'paht:issuer:subject' notation.
        _ssl_attr_sorted+=("${_key_path}:${_key_issuer_filter}:${_last_subject}")

        printf "  \\t         (%s)\\n" "${_key_path_name}"
        printf "  \\t         (\\e[0;33m%s\\e[m)\\n" "${_key_type}"
        printf "    S:(\\e[1;36m%s\\e[m):(\\e[1;39m%s\\e[m)\\n" "${_key_subject_hash}" "${_last_subject}"
        printf "    I:(\\e[1;36m%s\\e[m):(\\e[1;30m%s\\e[m)\\n" "${_key_issuer_hash}" "${_key_issuer_filter}"

        _logger "info" \
          "$_FUNCTION_ID()" \
          "found relationship: $_last_subject <==> $_key_issuer_filter"

        _last_subject="$_key_issuer_filter"

        _ssl_keep_num=$((_ssl_keep_num+1))

      else

        if [[ "${_key_issuer_filter}" == "${_key_subject_filter}" ]] ; then

          # shellcheck disable=SC2034
          _key_type="Root Certificate"
          # shellcheck disable=SC2034
          _key_type_root="true"

          # shellcheck disable=SC2034
          _key_type_root_inter="true"
          _root_certificate_meta="$_key_issuer_filter"

        fi

      fi

      if [[ "${_key_type_inter}" == "true" ]] && [[ "${_key_type_root}" == "true" ]] ; then

        if [[ ! "${_key_issuer_filter}" == "${_key_subject}" ]] ; then

          if [[ ! "${_key_subject}" == *"."* ]] ; then

            if [[ ! "${_key_issuer_filter}" == "${_root_certificate_meta}" ]] ; then

              # shellcheck disable=SC2034
              _key_type_root_inter_visible="true"

            fi

          fi

        fi

      fi

    fi

    done

    _ssl_attr_num=$((_ssl_attr_num+1))

  done

  echo

  # Copy the sorted contents of the temporary (local) array to the global array.
  # shellcheck disable=SC2034
  ssl_attr_sorted=("${_ssl_attr_sorted[@]}")

  return $_STATE

}
