#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: sslGetSha256()
#
# Description:
#
# Usage:
#   sslGetSha256
#
# Examples:
#   sslGetSha256
#

function sslGetSha256() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="sslGetSha256"
  local _STATE=0

  local _hash_type="$1"
  local _cert="$2"

  _hash=""

  if [[ "$_hash_type" == "issuer" ]] ; then

    _hash=$(openssl x509 -noout -issuer_hash -in "$_cert")

  elif [[ "$_hash_type" == "subject" ]] ; then

    # shellcheck disable=SC2034
    _hash=$(openssl x509 -noout -subject_hash -in "$_cert")

  fi

  return $_STATE

}
