#!/usr/bin/env bash

# shellcheck shell=bash

################################################################################
######################### Main function (script init) ##########################
################################################################################

function __main__() {

  local _FUNCTION_ID="__main__"
  local _STATE="0"

  # Stores the current date.
  readonly _cdate=$(date +%Y%m%d)

  # Variables related to the log file. Divided into three parts due
  # to the better possibility of manipulation for the user.
  # shellcheck disable=SC2154
  readonly _log_directory="${_rel}/log"
  # shellcheck disable=SC2154
  readonly _log_file="${_init_name}.${_cdate}.log"
  readonly _log_stdout="${_log_directory}/stdout.log"
  readonly _log_path="${_log_directory}/${_log_file}"

  # Path to import file.
  # shellcheck disable=SC2154
  readonly _import_path="${_src}/import"

  # External configuration file (-c|--config script param).
  # shellcheck disable=SC2034
  config=""
  # shellcheck disable=SC2034
  load_state="0"

  # Declaration of output variables (--debug and --verbose params).
  stdout_mode=""
  # Enable/disable output colors.
  # shellcheck disable=SC2034
  s_color="true"

  # Declaration of total execution time.
  time_tracking="false"
  export _cmdtime_state="0"

  # Add Root Certificate to the certificate chain.
  _with_root="0"

  # Global cert path.
  _cert_path=""

  # Default output chain file.
  _output_shm=$(date +%s | md5sum | awk '{print $1}')
  # shellcheck disable=SC2154
  _output_fd="${_chs}/${_output_shm}.crt"

  # Remote chain (default value).
  # shellcheck disable=SC2034
  _remote_chain_domain=""
  _remote_chain_state="0"
  # shellcheck disable=SC2034
  _remote_chain_fd="remote_chain.pem"
  _remote_chain_dir=""
  _remote_chain_dir_fpath=""

  # Set main ssl certificates system path.
  readonly _system_ca_path="/etc/ssl/certs"

  pem_cert_full_path=""

  # We place here used commands at script runtime, as strings to anything
  # unnecessarily run.
  readonly commands=("basename" "dirname" "stat" "date" "grep" "cut" \
                     "sed" "gzip" "tar" "openssl")

  # If you intend to specify the full path to the command we do it like:
  # readonly exec_gzip="/bin/gzip"

  # Stores the names of the missing commands.
  missing_hash=()
  missing_counter="0"

  for i in "${commands[@]}" ; do

    if [[ -n "$i" ]] ; then

      hash "$i" >/dev/null 2>&1 ; state="$?"

      # If the command was not found put it in the array
      if [[ "$state" -ne 0 ]] ; then

        missing_hash+=("$i")
        ((missing_counter++))

      fi

    fi

  done

  # It is a good idea to terminate the script at this stage
  # with information for the user to fix the errors if at least one
  # of the required commands in the commands array is not found.
  if [[ "$missing_counter" -gt 0 ]] ; then

    printf "not found in PATH: %s\\n" "${missing_hash[*]}" >&2
    _exit_ "1"

  fi

  if [[ "$time_tracking" == "true" ]] ; then
    _begtime=$(date +%s) ; fi

  # shellcheck disable=SC2154
  _logger "init" \
    "init '${_init_name}' in '${_init_directory}'" && \
  _logger "info" \
    "__init_params[] = (${__init_params[*]})," \
    "__script_params[] = (${__script_params[*]})"

  # Include import file.
  _load "null" "$_import_path"

  # Specifies the call parameters of the script, the exact description
  # can be found in _help_ and file README.md.
  local _short_opt="i:o:"
  local _long_opt="help,debug,in:,out:,with-root"

  _GETOPT_PARAMS=$(getopt -o "${_short_opt}" --long "${_long_opt}" \
                   -n "${_init_name}" -- "${__script_params[@]}")

  # With this structure, in the case of problems with the parameters placed
  # in the _GETOPT_PARAMS variable we finish the script. Keep this in mind
  # because it has some consequences - the __main __() function will not be
  # executed.

  # Ends an error if the parameter or its argument is not valid.
  _getopt_state="$?"
  if [ "$_getopt_state" != 0 ] ; then
    _exit_ "1"
  # Ends if no parameter is specified.
  elif [[ "${#__script_params[@]}" -eq 0 ]] ; then
    _exit_ "0"
  fi

  eval set -- "$_GETOPT_PARAMS"
  while true ; do

    case $1 in

      --help)

        _help_

        shift ; _exit_ "0" ;;

      --debug)

        export stdout_mode="debug"

        shift ;;

      -i|--in)

        if [[ $2 == *"https://"* ]]; then

          _remote_chain_state="1"
          _remote_domain=$(echo "$2" | sed -e 's|^[^/]*//||' -e 's|/.*$||')

        else

          _input_fd=$(pwd)/"$2"

          if [[ -e "$_input_fd" ]] || \
             [[ -d "$_input_fd" ]] ; then

            ssl_delivered_certificates+=("$_input_fd")

          fi

        fi

        shift 2 ;;

      -o|--out)

        _output_fd="$2"

        shift 2 ;;

      --with-root)

        # shellcheck disable=SC2034
        _with_root="1"

        shift ;;

      *)

        if [[ "$2" == "-" ]] || [[ -n "$2" ]] ; then

          printf "%s: invalid option -- '%s'\\n" "$_init_name" "$2"
          _exit_ "1"

        # elif [[ -z "$2" ]] ; then break ; fi
        else break ; fi

        ;;

    esac

  done

  # If you run the script in debug mode, the information
  # will be displayed on the screen from this point.
  if [[ "$stdout_mode" == "debug" ]] ; then

    _logger "info" \
      "${_FUNCTION_ID}()" \
      "starting debug mode"

  fi

  # Running tasks before start user functions.
  _before_init

  ################################# USER SPACE #################################
  # ````````````````````````````````````````````````````````````````````````````
  # Put here all your variable declarations, function calls
  # and all the other code blocks.

  # shellcheck disable=SC2034
  # Generate random value.
  _random=$(date +"%s")

  # Array that stores the names of variables used that are part of the script
  # call parameters (_GETOPT_PARAMS). Useful when checking whether all
  # or selected parameters without which the script can not work properly
  # have been used. Do not add the load_state variable to the _opt_values array,
  # which is supported above.
  if [[ "$_remote_chain_state" -eq 0 ]] ; then

    _opt_values=("ssl_delivered_certificates" "_output_fd")

  fi

  # Checking the value of the variables (if they are unset or empty):
  #   - variables for call parameters
  #   - variables from the additional configuration files
  if [[ "${#_opt_values[@]}" -ne 0 ]] ; then

    for i in "${_opt_values[@]}" ; do

      _i="" ; eval _i='$'"$i"

      _logger "info" \
        "${_FUNCTION_ID}()" \
        "$i: '$_i'"

      if [[ -z "$_i" ]] ; then

        _sprintf "stop" "error of argument value: '$i' is unset or empty"

        _logger "stop" \
          "${_FUNCTION_ID}()" \
          "error of argument value: '$i' is unset or empty"

      fi

    done

  fi

  # Define array with empty values.
  # shellcheck disable=SC2034
  ssl_delivered_certificates_list=()
  # shellcheck disable=SC2034
  ssl_attr=()
  # shellcheck disable=SC2034
  ssl_attr_sorted=()

  # Define the maximum row size in certificate file.
  # shellcheck disable=SC2034
  fixed_row_size="64"

  # Strings that identifies the certificates.
  # shellcheck disable=SC2034
  ssl_beg_cert_id="-----BEGIN CERTIFICATE-----"
  # shellcheck disable=SC2034
  ssl_end_cert_id="-----END CERTIFICATE-----"

  # Temporary file extension.
  # shellcheck disable=SC2034
  fext="tmp"

  if [[ "$_remote_chain_state" -eq 1 ]] ; then

    _remote_chain_dir=$(pwd)
    _remote_chain_dir_fpath="${_remote_chain_dir}/${_remote_domain}"

    sslRemoteChain "${_remote_domain}"

    # shellcheck disable=SC2012
    _input_fd=$(ls "$_remote_chain_dir_fpath" | head -n 1)

    ssl_delivered_certificates+=("${_remote_chain_dir_fpath}")

  fi

  : >"$_output_fd" && \
  _state="0" || _state="1"

  if [[ "$_state" -eq "0" ]] ; then

    _logger "info" \
      "$_FUNCTION_ID()" \
      "clear the contents of the '$_output_fd' properly"

    if [[ "${#ssl_delivered_certificates[@]}" -ne "0" ]] ; then

      # Stores certificates.
      _ssl_cert_stack=""

      # We do if you provide a server certificate.
      if [[ "${#ssl_delivered_certificates[@]}" -eq "1" ]] ; then

        for i in "${ssl_delivered_certificates[@]}" ; do

          if [[ -f "$i" ]] ; then

            _uri_path=$(openssl x509 -noout -text -in "$i" | grep "CA Issuers - URI:" | cut -d ":" -f2-)

            if [[ -z "$_uri_path" ]] ; then

              _sprintf "stop" "incorrect CA Issuers for $i"

              _logger "stop" \
                "$_FUNCTION_ID()" \
                "incorrect CA Issuers for $i" && _exit_ "1"

            fi

            # shellcheck disable=SC2034
            _cert_path="$(dirname "$(readlink -f "$i")")"

            if [[ "$_remote_chain_state" -eq 0 ]] ; then

              sslGetUriCA "$_uri_path" "$i"

              sslGetSha256 "issuer" "$pem_cert_full_path"

              sslGetSysCA

              ssl_delivered_certificates+=("$pem_cert_full_path" "$_root_ca_path")

            fi

          fi

        done

      fi

      # shellcheck disable=SC2034
      if [[ "$_remote_chain_state" -eq 1 ]] && [[ "$_with_root" -eq 1 ]] ; then

        _cert_path="$_remote_chain_dir_fpath"

        # shellcheck disable=SC2012
        _remote_chain_dir_fpath_last=$(ls "$_remote_chain_dir_fpath" | tail -n 1)

        sslGetSha256 "issuer" "${_remote_chain_dir_fpath}/${_remote_chain_dir_fpath_last}"

        sslGetSysCA

      fi

      # For better control of the log file (do not use _sprintf).
      for i in "${ssl_delivered_certificates[@]}" ; do

        if [[ -f "$i" ]] ; then

          sslSetRowSize "$i"

          sslCheck "$i"

          _logger "info" \
            "$_FUNCTION_ID()" \
            "script param '$i' is a file"

        elif [[ -d "$i" ]] ; then

          _logger "info" \
            "$_FUNCTION_ID()" \
            "script param '$i' is a directory"

          # Remove last '/' for better compatibility.
          i="${i%/}"

          # shellcheck disable=SC2207
          _ssl_cert_stack=($(find "$i" -maxdepth 1 -type f -printf "%f\\n"))

          # shellcheck disable=SC2207
          IFS=$'\n' _ssl_cert_stack_tmp=($(sort <<<"${_ssl_cert_stack[*]}")); unset IFS

          for j in "${_ssl_cert_stack_tmp[@]}" ; do

            local _ssl_path_plus_name="${i}/${j}"

            sslSetRowSize "$_ssl_path_plus_name"

            sslCheck "$_ssl_path_plus_name"

            _logger "info" \
              "$_FUNCTION_ID()" \
              "script param '$i' is a file"

          done

        else

          # If the file/directory is not valid.
          _sprintf "stop" "incorrect file/directory: $i"

          _logger "stop" \
            "$_FUNCTION_ID()" \
            "incorrect file/directory: $i" && _exit_ "1"

        fi

      done

      # We pass without arguments to the function which processes array
      # directly in a function and assigned to the local array.
      sslInfo

      # We call the function responsible for creating the chain. Here when
      # calling anything special but inside the function refers to external array.
      sslChain

    fi

  else

    _sprintf "stop" "clear the contents of the '$_output_fd' failed"

    _logger "info" \
      "$_FUNCTION_ID()" \
      "clear the contents of the '$_output_fd' failed"

  fi

  # ````````````````````````````````````````````````````````````````````````````

  if [[ "$time_tracking" == "true" ]] ; then

    # Counting the execution time.
    _endtime=$(date +%s)
    _totaltime=$((_endtime - _begtime))

    # Print time header.
    printf '\e[m\e[1;39mTOTAL TIME: %dh:%dm:%ds\e[m\n' \
            $((_totaltime/3600)) $((_totaltime%3600/60)) $((_totaltime%60))

  fi

  return "$_STATE"

}
